### ISSUE TITLE
Latest activity sort no longer working

### ISSUE THREAD

**Issue by cat262** [UW-GAC/django-anvil-consortium-manager#281]
Hi Adrienne, it looks like the when I add an account to an uploader group now, on the activity page that it directs me to, the activities are no longer listed by chronological order: https://apps.gregorconsortium.org/anvil/group_account_membership/all/. I think they're now grouped by group? Previously, if I add an uploader, the latest action I performed would show up at the bottom of this page. Could you add back in the sort for latest activity? Or create a button that allows sorting by latest activity? Thanks!

**Comment by amstilp** [comment]
I think I did switch the sorting on the table. At some point, we're going to have to do a bigger overhaul of some of these views, since we'll have more records than we can easily manage in a table. It's also possible that this page will go away and it will direct you somewhere else - possibly to the group that you added someone to instead? Do you have any thoughts about where you'd like the "add account to group" form to direct you to after submitting?

**Comment by amstilp** [comment]
Second question -- how are you adding the account to the uploader group? There are a couple different buttons/links that will take you to pages to do that.

**Comment by cat262** [comment]
Hmm, for the first question, I think it was helpful to be directed to an activity log that showed my previous activity. That way I knew who I most recently added, if I added others already to the same group, and if I missed anybody. If I could be directed to the form that lets me add accounts to groups - with the activity log on the bottom of the page - I think that'd be the most helpful: https://apps.gregorconsortium.org/anvil/group_account_membership/new/

For the second question, I usually follow the following steps:
1. click on the dropdown menu for "Managed Groups"
2. select "Add an account to a group"
3. choose the appropriate group, paste the email account to add, then add the individual as a member.

**Comment by amstilp** [comment]
Unfortunately, I don't think I have the bandwidth to implement a specific "activity log" like you're describing. I could change the group-account membership view back to the previous behavior where it was sorting internally by pk (which effectively sorts by date). But again, that page will likely get very long soon, so we'll probably have to do something different anyway.

Have you looked at the ManagedGroup detail page? That has a list of accounts in the group (but again, with no date at this point). Go to "Managed Groups" -> "List groups" -> click on the name of the group of interest -> click on the dropdown that says "View active accounts in this group". Does that give you enough of what you'd like?

I have been considering having the forms redirect to the ManagedGroup detail page instead of to the full list of group-account memberships. As I said that list will get really long.

**Comment by amstilp** [comment]
I ended up adding the "last modified" date to the group-group membership table, the group-account membership table, and the workspace-group sharing table. You should be able to sort by it on the main List views for those models. You won't be able to sort by it in the dropdown menus on the GroupDetail or WorkspaceDetail pages, but it looks like you can. (That's a different issue I need to fix at some point.)

**Comment by amstilp** [comment]
Also noting -- it won't be available immediately in the consortium sites using this app, but it should be the next time I deploy updates.
